<a href="https://colab.research.google.com/github/shivankurr/colab/blob/main/mlpractical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import datetime as dt
now=dt.datetime.now()
print("Current date & time : ")
print(now.strftime("%Y-%m-%d %H:%M:%S"))


Current date & time : 
2023-05-09 12:04:38


In [ ]:
from math import pi
r=float(input("Enter the radius: "))
a=pi*r**2
ans=round(a,2)
print("Area of the circle is: "+str(a))
print("Area of the circle is: "+str(ans))

Enter the radius: 4
Area of the circle is: 50.26548245743669
Area of the circle is: 50.27


In [ ]:
fname=input("Enter first name: ")
lname=input("Enter last name: ")
print("Hello "+fname+" "+lname)

Enter first name: shivi
Enter last name: sharma
Hello shivi sharma


In [ ]:
import scipy as sp
import numpy as np
nums=np.random.randint(1,50,size=(1,15))[0]
print(nums)

[27 13  5 24 42 13  5 36 35 49 36 15  7 42 29]


In [ ]:
print("Mean is: ",np.mean(nums))
print("Median is: ",np.median(nums))

Mean is:  25.2
Median is:  27.0


In [ ]:

import pandas as pd
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.shape)
print(arr.dtype)


(5,)
int64


In [ ]:

d=np.random.normal(size=(2,3))
print(d)


[[ 0.72741442  1.149754   -1.32721965]
 [ 1.4560679  -0.85719449 -0.32546778]]


In [ ]:

s=pd.DataFrame(d)
print(s)


          0         1         2
0  0.727414  1.149754 -1.327220
1  1.456068 -0.857194 -0.325468


In [ ]:
 df1=pd.DataFrame(np.random.normal(size=(2,3)))
df2=pd.DataFrame(np.random.normal(size=(3,3)))
app=df1.append(df2)
print(app)


          0         1         2
0 -0.584511  1.230975  0.558765
1 -0.619434  0.322595 -1.710024
0  0.951567 -1.308824  0.164617
1 -0.918961 -0.303545  0.153410
2 -0.445339 -0.929527 -1.360224


<ipython-input-11-727774b92436>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  app=df1.append(df2)
